services:
  - type: web
    name: game-club-telegram-bot
    runtime: node
    buildCommand: apt-get update && apt-get install -y postgresql-client && npm ci
    startCommand: npm start
    envVars:
      - key: BACKEND_API_URL
        value: https://game-club-backend.onrender.com/api
      - key: BOT_API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: REPORT_CHAT_ID
        sync: false
      - key: REPORT_TIME
        value: "22:00"
      - key: DATABASE_URL
        sync: false
